# Generated by Django 2.1.7 on 2020-02-16 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50)),
                ('Description', models.CharField(blank=True, max_length=50)),
                ('image', models.FileField(blank=True, null=True, upload_to='service/images')),
                ('Date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('client_email', models.EmailField(max_length=200)),
                ('Cell', models.CharField(blank=True, max_length=200)),
                ('Address', models.CharField(blank=True, max_length=200)),
                ('City', models.CharField(blank=True, max_length=100)),
                ('State', models.CharField(blank=True, max_length=100)),
                ('zip', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True, max_length=300)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=300)),
                ('url', models.URLField(blank=True, max_length=300)),
                ('CommentText', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50)),
                ('LAT', models.CharField(blank=True, max_length=50)),
                ('LONG', models.CharField(blank=True, max_length=50)),
                ('Description', models.TextField(blank=True)),
                ('Attachments', models.FileField(blank=True, null=True, upload_to='service/files')),
                ('Date_created', models.DateTimeField(auto_now_add=True)),
                ('User', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=40)),
                ('Device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestAPI.Device')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('Title', models.CharField(blank=True, max_length=50)),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['Title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50)),
                ('Date_needed', models.DateField(default=None)),
                ('Address', models.CharField(blank=True, max_length=50)),
                ('City', models.CharField(blank=True, max_length=50)),
                ('State', models.CharField(blank=True, max_length=50)),
                ('Zip', models.CharField(blank=True, max_length=50)),
                ('Description', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='service/files')),
                ('Date_created', models.DateTimeField(auto_now_add=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestAPI.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50)),
                ('Date_needed', models.DateField(default=None)),
                ('Address', models.CharField(blank=True, max_length=50)),
                ('City', models.CharField(blank=True, max_length=50)),
                ('State', models.CharField(blank=True, max_length=50)),
                ('Zip', models.CharField(blank=True, max_length=50)),
                ('WorkDescription', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='service/files')),
                ('Date_created', models.DateTimeField(auto_now_add=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestAPI.Categories')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='manager',
            unique_together={('User', 'Title')},
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('name', 'client_email')},
        ),
    ]
